server:
  port: 8088

#配置springboot的热部署
spring:
  thymeleaf:
    cache: false
  devtools:
    restart:
      enabled: true
      additional-paths: src/main  # 需要重启的目录

#mybatis:
#  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.xtt.shoprpcprovider
#
#pagehelper
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
